### ISSUE TITLE
you have typo

### ISSUE THREAD

**Issue by leewoooo** [tienbm90/simple-jwt-auth#2]
https://github.com/tienbm90/simple-jwt-auth/blob/dfec513cea08c9676d2e569eaeb2539e29c0d68e/auth/token.go#L103

//get the token from the request body
func ExtractToken(r *http.Request) string {

request body -> request header

**Comment by tienbm90** [comment]
I fixed the error in  commit [b506a06](https://github.com/tienbm90/simple-jwt-auth/commit/b506a06eda746c25d752b727fb0658ec8ff052fd)
